mysql:
  packages:
    mariadb:
      - MariaDB-server
      - MariaDB-client
      - MySQL-python
    mysql:
      - mysql-server
      - mysql
      - MySQL-python
  socket: /var/lib/mysql/mysql.sock
  datadir: /var/lib/mysql
  log_error: /var/log/mysql/error.log
  pid_file: /var/run/mysqld/mysqld.pid
  config_path: /etc/my.cnf.d