---
- name: enable ipv6 with sysctl
  sysctl: name={{ item }} value=0 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when: ansible_os_family == 'RedHat'

- name: restart network
  service: name=network state=restarted
  when: ansible_os_family == 'RedHat'

- name: ensure nfs utilities are installed
  yum: name=nfs-utils state=installed
  when: ansible_os_family == 'RedHat'

- name: ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes
  when: ansible_os_family == 'RedHat'

- name: ensure nfslock is running
  service: name=nfslock state=started enabled=yes
  when: ansible_os_family == 'RedHat'

- name: ensure nfs is start on boot on el7
  service: name=nfs-server enabled=yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
