---
php:
  webserver:
    enabled: true
  version: 7.0
  ini:
    expose_php: "On"
    memory_limit: "1024M"
    max_execution_time: "60"
    max_input_time: "60"
    max_input_vars: "1000"
    realpath_cache_size: "32K"
    file_uploads: "On"
    upload_max_filesize: "10M"
    max_file_uploads: "20"
    post_max_size: "32M"
    date_timezone: "Europe/Berlin"
    allow_url_fopen: "On"
    sendmail_path: "/usr/sbin/sendmail -t -i"
    output_buffering: "4096"
    short_open_tag: "Off"
    disable_functions: []
    session_cookie_lifetime: 0
    session_gc_probability: 1
    session_gc_divisor: 1000
    session_gc_maxlifetime: 1440
    session_save_handler: files
    session_save_path: ''
    error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
    display_errors: "Off"
    display_startup_errors: "Off"
  fpm:
    # @todo php-fpm not is not tested
    enabled: false
    listen: "127.0.0.1:9000"
    listen_allowed_clients: "127.0.0.1"
    pm_max_children: 50
    pm_start_servers: 5
    pm_min_spare_servers: 5
    pm_max_spare_servers: 5
  opcache:
    ini:
      zend_extension: "opcache.so"
      enable: "1"
      enable_cli: "0"
      memory_consumption: "96"
      interned_strings_buffer: "16"
      max_accelerated_files: "4096"
      max_wasted_percentage: "5"
      validate_timestamps: "1"
      revalidate_path: "0"
      revalidate_freq: "2"
      max_file_size: "0"
      blacklist_filename: ""
      load_comments: "1"
  apcu:
    ini:
      enabled: true
      shm_size: "96M"
      enable_cli: "0"
