---
- name: Create project directory and set its permissions
  become: true
  file:
    path: "{{ symfony_root_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: empty project directory
  become: true
  file:
    path: "{{ symfony_root_dir }}/*"
    state: absent

- name: Checkout Git repository
  git:
    repo: https://github.com/symfony/symfony-standard.git
    dest: "{{ symfony_root_dir }}"
    force: yes
  register: repo_code

- name: Register code_changed variable
  set_fact:
    code_changed: repo_code.changed

- name: Install Composer's dependencies
  composer:
    working_dir: "{{ symfony_root_dir }}"
    no_dev: no
  when: code_changed

- name: Fix var directory permissions
  file:
    path: "{{ symfony_var_dir }}"
    state: directory
    mode: 0777
    recurse: yes
  changed_when: false

- name: Copy Symfony parameters
  template:
    src: templates/parameters.yml.j2
    dest: "{{ symfony_root_dir }}/app/config/parameters.yml"

- name: Clear Symfony cache
  command: '{{ symfony_console_path }} cache:clear --env={{ symfony_env }}'
  when: code_changed

- name: Create DB if not exists
  command: '{{ symfony_console_path }} doctrine:database:create --if-not-exists'
  register: db_create_result
  changed_when: "not db_create_result.stdout|search('already exists. Skipped')"
