---
- name: add apt key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  when: ansible_os_family == 'Debian'

- name: add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs.version }} {{ ansible_distribution_release | lower }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs.version }} {{ ansible_distribution_release | lower }} main"
  when: ansible_os_family == 'Debian'

- name: install node
  apt:
    name: nodejs
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: import rpm key
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_os_family == 'RedHat'

- name: add rpm repositories
  yum:
    name: "https://rpm.nodesource.com/pub_{{ nodejs.version }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: install node
  yum:
    name: nodejs
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: install global packages
  npm:
    name: '{{ item.name | default(item) }}'
    version: '{{ item.version | default("latest") }}'
    state: latest
    global: true
  environment:
    NPM_CONFIG_UNSAFE_PERM: "{{ item.unsafe_perm | default('false')}}"
  with_items:
    "{{ nodejs.packages | default([]) }}"
