#!/usr/bin/env ansible-playbook

- name: Default playbook
  hosts: all
  become: true
#  tasks:
#    - debug:
#        msg: "{{ ansible_distribution_release|lower }}"

  roles:
    - common
    - nfs
    - firewall
    - apache
    - php
    - composer
    - python-pip
    - mysql
    - nodejs
    - open-jdk
    - rabbitmq

    - deploy-handy_de
